# is a organization repository
organization: false

# site title
title: Mirror

# github user
user: fydy

# issue repository
repository: issue-blog

# multi-author
authors:

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: d#710bd50e411602f6a5c6318dd9b2a0fdbd08e3d

# posts per page
perpage: 7

order: CREATED_AT

ignores: "17,13"
